# Generated by Django 5.0.4 on 2024-04-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isTrash',
            field=models.BooleanField(default=False),
        ),
    ]
